---
title: "cpesrthemes"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

esr <- kpiESR::esr.pnl %>%
  group_by(Rentrée, kpi) %>%
  filter(Rentrée != 2019, 
         kpi %in% c("kpi.ETU.S.cycle.1.L","kpi.ETU.S.cycle.2.M","kpi.ETU.S.cycle.3.D")) %>%
  summarise(Effectifs = sum(valeur, na.rm=TRUE)) %>%
  mutate(Niveau = recode(kpi, 
                         "kpi.ETU.S.cycle.1.L" = "L",
                         "kpi.ETU.S.cycle.2.M" = "M",
                         "kpi.ETU.S.cycle.3.D" = "D"))
```

Collections d'aides pour la mise en forme des travaux de la CPESR.

## ggcpesrthemes

Package R pour la production de graphiques.

### Installation

```{r install, eval=FALSE}
devtools::install_github("cpesr/cpesrthemes", subdir="ggcpesrthemes")
```

### Utilisation

- Juste le thème

```{r utilisation.simple, warning=FALSE}
library(ggplot2)
library(ggcpesrthemes)
ggplot(esr, aes(x=Rentrée, y=Effectifs, color=Niveau, group=Niveau)) + 
  geom_line() + 
  theme_cpesr() 
```

- Thème et caption par défaut

```{r utilisation.cap, warning=FALSE}
library(ggplot2)
library(ggcpesrthemes)
ggplot(esr, aes(x=Rentrée, y=Effectifs, color=Niveau, group=Niveau)) + 
  geom_line() + 
  theme_cpesr_cap() 
```


- Thème et caption personnalisés

```{r utilisation.perso, warning=FALSE}
library(ggplot2)
library(ggcpesrthemes)
ggplot(esr, aes(x=Rentrée, y=Effectifs, color=Niveau, group=Niveau)) + 
  geom_line() + 
  theme_cpesr_cap(authors=c("Author One","Author Two"), 
              camille=FALSE, 
              licence="CC BY-SA",
              url="https://github.com/cpesr/cpesrthemes",
              source="https://data.enseignementsup-recherche.gouv.fr")
```

- Thème et caption personnalisés globalement

```{r utilisation.glob, warning=FALSE}
library(ggplot2)
library(ggcpesrthemes)

theme_cpesr_setup(authors=c("Author One","Author Two"), 
                  camille=FALSE, 
                  licence="CC BY-SA",
                  url="https://github.com/cpesr/cpesrthemes",
                  source="https://data.enseignementsup-recherche.gouv.fr")

ggplot(esr, aes(x=Rentrée, y=Effectifs, color=Niveau, group=Niveau)) + 
  geom_line() + 
  theme_cpesr_cap()
```

